# Generated by Django 4.1.9 on 2024-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_venue_alter_event_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_enddatetime',
            new_name='event_end_datetime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_startdatetime',
            new_name='event_start_datetime',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(to='event.organiser'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='events',
            field=models.ManyToManyField(to='event.event'),
        ),
    ]
